import os

ROOT_DIR = os.environ['DATA_ROOT'] if 'DATA_ROOT' in os.environ else '.'

TRANSE='TransE'

ML1M = 'ml1m'
LFM1M = 'lfm1m'

DATASETS = [ML1M, LFM1M]

USER = 'user'
PRODUCT = 'product'
ENTITY = 'entity'
RELATION = 'relation'
SELF_LOOP = 'self_loop'
PRODUCED_BY_PRODUCER = 'produced_by_producer'
PRODUCER = 'producer'

INTERACTION = {
    ML1M: "watched",
    LFM1M: "listened", 
}

MAIN_PRODUCT_INTERACTION = {
    ML1M: (PRODUCT, INTERACTION[ML1M]),
    LFM1M: (PRODUCT, INTERACTION[LFM1M])
}

# ML1M ENTITIES
CINEMATOGRAPHER = 'cinematographer'
PRODCOMPANY = 'prodcompany'
COMPOSER = 'composer'
CATEGORY = 'category'
ACTOR = 'actor'
COUNTRY = 'country'
WIKIPAGE = 'wikipage'
EDITOR = 'editor'
WRITTER = 'writter'
DIRECTOR = 'director'

# LASTFM ENTITIES
ARTIST = 'artist'
ENGINEER = 'engineer'
GENRE = 'genre'

# ML1M RELATIONS
DIRECTED_BY_DIRECTOR = 'directed_by_director'
PRODUCED_BY_COMPANY = 'produced_by_prodcompany'
STARRED_BY_ACTOR = 'starred_by_actor'
RELATED_TO_WIKIPAGE = 'related_to_wikipage'
EDITED_BY_EDITOR = 'edited_by_editor'
WROTE_BY_WRITTER = 'wrote_by_writter'
CINEMATOGRAPHY_BY_CINEMATOGRAPHER = 'cinematography_by_cinematographer'
COMPOSED_BY_COMPOSER = 'composed_by_composer'
PRODUCED_IN_COUNTRY = 'produced_in_country'
BELONG_TO_CATEGORY = 'belong_to_category'

# LASTFM RELATIONS
MIXED_BY_ENGINEER = 'mixed_by_engineer'
FEATURED_BY_ARTIST = 'featured_by_artist'
BELONG_TO_GENRE = 'belong_to_genre'


ENTITY_LIST = {
    ML1M: [USER, PRODUCT, ACTOR, DIRECTOR, PRODCOMPANY, EDITOR, WRITTER, CINEMATOGRAPHER, COMPOSER, COUNTRY,
           CATEGORY, PRODUCER, WIKIPAGE],
    LFM1M: [USER, PRODUCT, ARTIST, ENGINEER, GENRE, PRODUCER],
}


RELATION_LIST = {
    ML1M: [INTERACTION[ML1M], BELONG_TO_CATEGORY, PRODUCED_BY_PRODUCER, DIRECTED_BY_DIRECTOR,
           PRODUCED_BY_COMPANY, STARRED_BY_ACTOR, EDITED_BY_EDITOR, WROTE_BY_WRITTER,
           CINEMATOGRAPHY_BY_CINEMATOGRAPHER, COMPOSED_BY_COMPOSER, PRODUCED_IN_COUNTRY,
           RELATED_TO_WIKIPAGE],
    LFM1M: [INTERACTION[LFM1M], BELONG_TO_GENRE, FEATURED_BY_ARTIST, MIXED_BY_ENGINEER, PRODUCED_BY_PRODUCER],
}

# REVERSED RELATIONS
REV_PREFIX = 'rev_'
REV_PRODUCED_BY_PRODUCER = REV_PREFIX + PRODUCED_BY_PRODUCER
REV_INTERACTION = {
    ML1M: REV_PREFIX + "watched",
    LFM1M: REV_PREFIX + "listened",
}

# REVERSED RELATIONS ML1M
REV_DIRECTED_BY_DIRECTOR = REV_PREFIX + DIRECTED_BY_DIRECTOR
REV_PRODUCED_BY_COMPANY = REV_PREFIX + PRODUCED_BY_COMPANY
REV_STARRED_BY_ACTOR = REV_PREFIX + STARRED_BY_ACTOR
REV_RELATED_TO_WIKIPAGE = REV_PREFIX + RELATED_TO_WIKIPAGE
REV_EDITED_BY_EDITOR = REV_PREFIX + EDITED_BY_EDITOR
REV_WROTE_BY_WRITTER = REV_PREFIX + WROTE_BY_WRITTER
REV_CINEMATOGRAPHY_BY_CINEMATOGRAPHER = REV_PREFIX + CINEMATOGRAPHY_BY_CINEMATOGRAPHER
REV_COMPOSED_BY_COMPOSER = REV_PREFIX + COMPOSED_BY_COMPOSER
REV_PRODUCED_IN_COUNTRY = REV_PREFIX + PRODUCED_IN_COUNTRY
REV_BELONG_TO_CATEGORY = REV_PREFIX + BELONG_TO_CATEGORY

#REVERSED RELATIONS LFM1M
REV_MIXED_BY_ENGINEER = REV_PREFIX + MIXED_BY_ENGINEER
REV_FEATURED_BY_ARTIST = REV_PREFIX + FEATURED_BY_ARTIST
REV_BELONG_TO_GENRE = REV_PREFIX + BELONG_TO_GENRE

# UCPR SPECIFIC RELATIONs
KG_RELATION = {
    ML1M: {
        USER: {
            INTERACTION[ML1M]: PRODUCT,
        },
        ACTOR: {
            STARRED_BY_ACTOR: PRODUCT,
        },
        DIRECTOR: {
            DIRECTED_BY_DIRECTOR: PRODUCT,
        },
        PRODUCT: {
            INTERACTION[ML1M]: USER,
            PRODUCED_BY_COMPANY: PRODCOMPANY,
            PRODUCED_BY_PRODUCER: PRODUCER,
            EDITED_BY_EDITOR: EDITOR,
            WROTE_BY_WRITTER: WRITTER,
            CINEMATOGRAPHY_BY_CINEMATOGRAPHER: CINEMATOGRAPHER,
            BELONG_TO_CATEGORY: CATEGORY,
            DIRECTED_BY_DIRECTOR: DIRECTOR,
            STARRED_BY_ACTOR: ACTOR,
            COMPOSED_BY_COMPOSER: COMPOSER,
            PRODUCED_IN_COUNTRY: COUNTRY,
            RELATED_TO_WIKIPAGE: WIKIPAGE,
        },
        PRODCOMPANY: {
            PRODUCED_BY_COMPANY: PRODUCT,
        },
        COMPOSER: {
            COMPOSED_BY_COMPOSER: PRODUCT,
        },
        PRODUCER: {
            PRODUCED_BY_PRODUCER: PRODUCT,
        },
        WRITTER: {
            WROTE_BY_WRITTER: PRODUCT,
        },
        EDITOR: {
            EDITED_BY_EDITOR: PRODUCT,
        },
        CATEGORY: {
            BELONG_TO_CATEGORY: PRODUCT,
        },
        CINEMATOGRAPHER: {
            CINEMATOGRAPHY_BY_CINEMATOGRAPHER: PRODUCT,
        },
        COUNTRY: {
            PRODUCED_IN_COUNTRY: PRODUCT,
        },
        WIKIPAGE: {
            RELATED_TO_WIKIPAGE: PRODUCT,
        }
    },
    LFM1M: {
        USER: {
            INTERACTION[LFM1M]: PRODUCT,
        },
        ARTIST: {
            FEATURED_BY_ARTIST: PRODUCT,
        },
        ENGINEER: {
            MIXED_BY_ENGINEER: PRODUCT,
        },
        PRODUCT: {
            INTERACTION[LFM1M]: USER,
            PRODUCED_BY_PRODUCER: PRODUCER,
            FEATURED_BY_ARTIST: ARTIST,
            MIXED_BY_ENGINEER: ENGINEER,
            BELONG_TO_GENRE: GENRE,
        },
        PRODUCER: {
            PRODUCED_BY_PRODUCER: PRODUCT,
        },
        GENRE: {
            BELONG_TO_GENRE: PRODUCT,
        },
    },
}

# 0 is reserved to the main relation, 1 to mention
PATH_PATTERN = {
    ML1M: {
        0: ((None, USER), (INTERACTION[ML1M], PRODUCT), (INTERACTION[ML1M], USER), (INTERACTION[ML1M], PRODUCT)),
        2: ((None, USER), (INTERACTION[ML1M], PRODUCT), (CINEMATOGRAPHY_BY_CINEMATOGRAPHER, CINEMATOGRAPHER), (CINEMATOGRAPHY_BY_CINEMATOGRAPHER, PRODUCT)),
        3: ((None, USER), (INTERACTION[ML1M], PRODUCT), (PRODUCED_BY_COMPANY, PRODCOMPANY), (PRODUCED_BY_COMPANY, PRODUCT)),
        4: ((None, USER), (INTERACTION[ML1M], PRODUCT), (COMPOSED_BY_COMPOSER, COMPOSER), (COMPOSED_BY_COMPOSER, PRODUCT)),
        5: ((None, USER), (INTERACTION[ML1M], PRODUCT), (BELONG_TO_CATEGORY, CATEGORY), (BELONG_TO_CATEGORY, PRODUCT)),
        7: ((None, USER), (INTERACTION[ML1M], PRODUCT), (STARRED_BY_ACTOR, ACTOR), (STARRED_BY_ACTOR, PRODUCT)),
        8: ((None, USER), (INTERACTION[ML1M], PRODUCT), (EDITED_BY_EDITOR, EDITOR), (EDITED_BY_EDITOR, PRODUCT)),
        9: ((None, USER), (INTERACTION[ML1M], PRODUCT), (PRODUCED_BY_PRODUCER, PRODUCER), (PRODUCED_BY_PRODUCER, PRODUCT)),
        10: ((None, USER), (INTERACTION[ML1M], PRODUCT), (WROTE_BY_WRITTER, WRITTER), (WROTE_BY_WRITTER, PRODUCT)),
        11: ((None, USER), (INTERACTION[ML1M], PRODUCT), (DIRECTED_BY_DIRECTOR, DIRECTOR), (DIRECTED_BY_DIRECTOR, PRODUCT)),
        12: ((None, USER), (INTERACTION[ML1M], PRODUCT), (PRODUCED_IN_COUNTRY, COUNTRY), (PRODUCED_IN_COUNTRY, PRODUCT)),
        13: ((None, USER), (INTERACTION[ML1M], PRODUCT), (RELATED_TO_WIKIPAGE, WIKIPAGE), (RELATED_TO_WIKIPAGE, PRODUCT)),
    },
    LFM1M: {
        0: ((None, USER), (INTERACTION[LFM1M], PRODUCT), (INTERACTION[LFM1M], USER), (INTERACTION[LFM1M], PRODUCT)),
        2: ((None, USER), (INTERACTION[LFM1M], PRODUCT), (BELONG_TO_GENRE, GENRE), (BELONG_TO_GENRE, PRODUCT)),
        4: ((None, USER), (INTERACTION[LFM1M], PRODUCT), (FEATURED_BY_ARTIST, ARTIST), (FEATURED_BY_ARTIST, PRODUCT)),
        5: ((None, USER), (INTERACTION[LFM1M], PRODUCT), (MIXED_BY_ENGINEER, ENGINEER), (MIXED_BY_ENGINEER, PRODUCT)),
        6: ((None, USER), (INTERACTION[LFM1M], PRODUCT), (PRODUCED_BY_PRODUCER, PRODUCER), (PRODUCED_BY_PRODUCER, PRODUCT)),
    },

}
